spring:
  sql:
    init:
      mode: always # Garante que o data.sql será executado
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?useSSL=false&serverTimezone=UTC
    username: root # Usuário do MySQL
    password: root # Senha do MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
